### ISSUE TITLE
add youtube-dl-batch for linux

### ISSUE THREAD

**Issue by candrapersada** [Schytheron/youtube-dl-bats#1]
add youtube-dl-batch and yt-dlp-batch for linux?

**Comment by edinsuta** [comment]
I have no plans for adding alternative files for Linux as there are already a bunch of repositories out there for exactly this purpose (way more than for Windows releases). I suggest you use those instead (for example this https://jely2002.github.io/youtube-dl-gui/ that is cross-platform and comes with a GUI).
