### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by bluebrad** [Schytheron/youtube-dl-bats#2]
i used  youtube-dl-batch/ytdlBasic.bat  and it seams to work but nothing is happening
not sure if youtube is blocking it or somthing

**Comment by edinsuta** [comment]
Can you further explain what you mean by this? Is the download just really slow? If so, it has been reported multiple times in recent times that there is an issue with `youtube-dl` where YouTube is throttling the speed making `youtube-dl` downloading really slow (https://github.com/ytdl-org/youtube-dl/issues/29326).

On the bright side, there exists a fork of the `youtube-dl` project called `yt-dlp` (https://github.com/yt-dlp/yt-dlp). This project has a built-in workaround for the YouTube speed throttling allowing you to download YouTube videos at full speeds.

I have even made a separate repository, just like this one, that contains .bat files for the `yt-dlp` project instead (https://github.com/edinsuta/yt-dlp-batch). I suggest you use this until `youtube-dl` has found and implemented a workaround for this download speed throttling issue.

**Comment by bluebrad** [comment]
i would like to know if there is a way to sign in to youtube?

**Comment by edinsuta** [comment]
There is a way to sign in to YouTube to download private videos via `youtube-dl` if that is what you're referring to. You can do this by exporting browser cookies and using the `--cookies` parameter in `youtube-dl`. Here's a guide on how to do it: https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-pass-cookies-to-youtube-dl
